<?php
declare(strict_types=1);

namespace App\Services;

use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * v22p54 — Branded XLSX export service.
 * Replaces the v22p45-era CSV streamers across every admin list.
 *
 * Conventions:
 *   - Row 1: agency logo (if present) + report title in brand colour
 *   - Row 2: subtitle (agency name + generated date)
 *   - Row 4: column headers (white text, brand-color fill, bold)
 *   - Row 5+: data with alternating row colour
 *   - Auto-width every column
 *   - Header row frozen
 *   - Footer row: "Generated by KiddieTrac for <Agency Name> · <date>"
 */
final class XlsxExportService
{
    public function build(int $agencyId, string $title, array $columns, iterable $rowProvider, array $opts = []): array
    {
        $agency = DB::table('agencies')->where('id', $agencyId)->first();
        $primary = ltrim($agency->brand_primary_color ?? '#1F6080', '#');
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle(substr(preg_replace('/[^A-Za-z0-9 ]/', '', $title), 0, 30) ?: 'Export');

        $colCount = count($columns);
        $lastCol = $this->colLetter($colCount);

        // Title row
        $sheet->setCellValue('A1', $title);
        $sheet->mergeCells("A1:{$lastCol}1");
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(18)->getColor()->setRGB('FFFFFF');
        $sheet->getStyle('A1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB($primary);
        $sheet->getStyle('A1')->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getRowDimension(1)->setRowHeight(36);

        // Subtitle row
        $subtitle = ($agency->name ?? 'KiddieTrac') . ' · Generated ' . now()->format('F j, Y \a\t g:i A');
        if (!empty($opts['period'])) $subtitle .= ' · Period: ' . $opts['period'];
        $sheet->setCellValue('A2', $subtitle);
        $sheet->mergeCells("A2:{$lastCol}2");
        $sheet->getStyle('A2')->getFont()->setSize(10)->getColor()->setRGB('6B7280');
        $sheet->getRowDimension(2)->setRowHeight(20);

        // Header row at row 4
        $headerRow = 4;
        $colIdx = 1;
        foreach ($columns as $col) {
            $cell = $this->colLetter($colIdx) . $headerRow;
            $sheet->setCellValue($cell, $col['header']);
            $colIdx++;
        }
        $sheet->getStyle("A{$headerRow}:{$lastCol}{$headerRow}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 11],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $primary]],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER, 'horizontal' => Alignment::HORIZONTAL_LEFT],
            'borders' => ['bottom' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['rgb' => '1F2937']]],
        ]);
        $sheet->getRowDimension($headerRow)->setRowHeight(26);
        $sheet->freezePane('A' . ($headerRow + 1));

        // Data rows
        $rowNum = $headerRow + 1;
        $dataCount = 0;
        foreach ($rowProvider as $row) {
            $colIdx = 1;
            foreach ($columns as $col) {
                $cell = $this->colLetter($colIdx) . $rowNum;
                $value = $row[$col['key']] ?? '';
                if (isset($col['format'])) {
                    if ($col['format'] === 'money') {
                        $sheet->setCellValue($cell, (float) ($value ?: 0));
                        $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('"$"#,##0.00');
                    } elseif ($col['format'] === 'date') {
                        $sheet->setCellValue($cell, $value ? \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel(strtotime($value)) : '');
                        $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('yyyy-mm-dd');
                    } elseif ($col['format'] === 'datetime') {
                        $sheet->setCellValue($cell, $value ? \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel(strtotime($value)) : '');
                        $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('yyyy-mm-dd hh:mm');
                    } else {
                        $sheet->setCellValue($cell, $value);
                    }
                } else {
                    $sheet->setCellValue($cell, $value);
                }
                $colIdx++;
            }
            // alternating row fill
            if ($dataCount % 2 === 1) {
                $sheet->getStyle("A{$rowNum}:{$lastCol}{$rowNum}")->getFill()
                    ->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('F9FAFB');
            }
            $sheet->getStyle("A{$rowNum}:{$lastCol}{$rowNum}")->applyFromArray([
                'borders' => ['bottom' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'E5E7EB']]],
                'font' => ['size' => 10],
            ]);
            $rowNum++;
            $dataCount++;
        }

        // Footer row
        if (!empty($opts['totals_row'])) {
            $colIdx = 1;
            foreach ($columns as $col) {
                if (isset($opts['totals_row'][$col['key']])) {
                    $cell = $this->colLetter($colIdx) . $rowNum;
                    $sheet->setCellValue($cell, $opts['totals_row'][$col['key']]);
                    if (isset($col['format']) && $col['format'] === 'money') {
                        $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('"$"#,##0.00');
                    }
                }
                $colIdx++;
            }
            $sheet->getStyle("A{$rowNum}:{$lastCol}{$rowNum}")->applyFromArray([
                'font' => ['bold' => true, 'size' => 11],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'F3F4F6']],
                'borders' => ['top' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['rgb' => $primary]]],
            ]);
            $rowNum++;
        }

        // Generated-by footer
        $rowNum += 2;
        $sheet->setCellValue("A{$rowNum}", 'Generated by KiddieTrac for ' . ($agency->name ?? '') . ' · ' . now()->format('Y-m-d H:i'));
        $sheet->mergeCells("A{$rowNum}:{$lastCol}{$rowNum}");
        $sheet->getStyle("A{$rowNum}")->getFont()->setSize(9)->setItalic(true)->getColor()->setRGB('9CA3AF');

        // Auto width
        for ($i = 1; $i <= $colCount; $i++) {
            $letter = $this->colLetter($i);
            $width = $columns[$i - 1]['width'] ?? null;
            if ($width) {
                $sheet->getColumnDimension($letter)->setWidth((float) $width);
            } else {
                $sheet->getColumnDimension($letter)->setAutoSize(true);
            }
        }

        $tmp = tempnam(sys_get_temp_dir(), 'kt-xlsx-');
        $writer = new Xlsx($spreadsheet);
        $writer->save($tmp);
        $body = file_get_contents($tmp);
        unlink($tmp);
        return ['body' => $body, 'rows' => $dataCount];
    }

    public function download(int $agencyId, string $title, string $filename, array $columns, iterable $rows, array $opts = []): Response
    {
        $built = $this->build($agencyId, $title, $columns, $rows, $opts);
        return new Response($built['body'], 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            'Cache-Control' => 'no-cache',
        ]);
    }

    /**
     * Build a downloadable XLSX template for bulk import.
     * Headers row + 1-2 sample rows + an instruction row.
     */
    public function template(int $agencyId, string $title, string $filename, array $columns, array $sampleRows = [], array $instructions = []): Response
    {
        $rows = $sampleRows;
        $opts = [];
        $out = $this->build($agencyId, $title . ' — Import Template', $columns, $rows, $opts);
        // re-open to add instructions sheet
        $tmp = tempnam(sys_get_temp_dir(), 'kt-xlsx-tpl-');
        file_put_contents($tmp, $out['body']);
        $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
        $spreadsheet = $reader->load($tmp);
        $instr = $spreadsheet->createSheet();
        $instr->setTitle('Instructions');
        $instr->setCellValue('A1', 'How to use this template');
        $instr->getStyle('A1')->getFont()->setBold(true)->setSize(16);
        $row = 3;
        foreach ($instructions as $i) {
            $instr->setCellValue("A{$row}", '• ' . $i);
            $instr->getStyle("A{$row}")->getAlignment()->setWrapText(true);
            $instr->getRowDimension($row)->setRowHeight(-1);
            $row++;
        }
        $instr->getColumnDimension('A')->setWidth(100);
        $writer = new Xlsx($spreadsheet);
        $writer->save($tmp);
        $body = file_get_contents($tmp);
        unlink($tmp);
        return new Response($body, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    private function colLetter(int $n): string
    {
        $s = '';
        while ($n > 0) {
            $m = ($n - 1) % 26;
            $s = chr(65 + $m) . $s;
            $n = (int) (($n - $m) / 26);
        }
        return $s;
    }
}
