<!doctype html>
<html><head><meta charset="utf-8"><title>CWELCC Monthly Report — {{ $month }}</title>
<style>
  body { font-family: 'DejaVu Sans', sans-serif; color: #1F2937; font-size: 10pt; }
  .header { border-bottom: 2px solid #1F6080; padding-bottom: 10px; margin-bottom: 16px; }
  .header h1 { color: #1F6080; margin: 0; font-size: 20pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td { padding: 6px 8px; border-bottom: 1px solid #E5E7EB; font-size: 9pt; }
  th { background: #F9FAFB; text-align: left; color: #6B7280; text-transform: uppercase; font-size: 8pt; }
  td.amount { text-align: right; font-variant-numeric: tabular-nums; }
  .totals { font-weight: bold; border-top: 2px solid #1F6080; background: #F0F9FF; }
  .footer { margin-top: 30px; font-size: 8.5pt; color: #6B7280; }
</style></head>
<body>
  <div class="header">
    <h1>CWELCC Monthly Report</h1>
    <div>{{ $agency->name ?? 'KiddieTrac' }} · {{ $month }}</div>
  </div>
  <table>
    <thead>
      <tr><th>Child</th><th>Family</th><th>Centre</th><th class="amount">Gross fee</th><th class="amount">Rate</th><th class="amount">Subsidy</th><th class="amount">Parent</th></tr>
    </thead>
    <tbody>
      @forelse ($rows as $r)
        <tr>
          <td>{{ $r['child_name'] }}</td>
          <td>{{ $r['family_name'] }}</td>
          <td>{{ $r['centre_name'] }}</td>
          <td class="amount">${{ number_format($r['gross_fee'], 2) }}</td>
          <td class="amount">{{ $r['subsidy_rate'] }}%</td>
          <td class="amount">${{ number_format($r['subsidy_amount'], 2) }}</td>
          <td class="amount">${{ number_format($r['parent_portion'], 2) }}</td>
        </tr>
      @empty
        <tr><td colspan="7" style="text-align:center; color:#9CA3AF;">No CWELCC-enrolled families for this month.</td></tr>
      @endforelse
      <tr class="totals">
        <td colspan="3"><strong>TOTALS ({{ $totals['child_count'] }} children)</strong></td>
        <td class="amount">${{ number_format($totals['gross'], 2) }}</td>
        <td></td>
        <td class="amount">${{ number_format($totals['subsidy'], 2) }}</td>
        <td class="amount">${{ number_format($totals['parent'], 2) }}</td>
      </tr>
    </tbody>
  </table>
  <div class="footer">
    Generated by KiddieTrac on {{ now()->format('F j, Y \a\t g:i A') }}.<br>
    For submission to the Ministry of Education (Ontario) CWELCC program.
  </div>
</body></html>
