<!doctype html>
<html><head><meta charset="utf-8"><title>{{ $child->first_name }} {{ $child->last_name }} — Portfolio</title>
<style>
  body { font-family: 'DejaVu Sans', sans-serif; color: #1F2937; font-size: 10.5pt; }
  .cover { text-align: center; padding: 60px 30px 30px; border-bottom: 4px solid #1F6080; }
  .cover h1 { font-size: 28pt; margin: 0; color: #1F6080; }
  .cover .sub { color: #6B7280; margin-top: 6px; }
  h2 { color: #1F6080; border-bottom: 1px solid #1F6080; padding-bottom: 4px; font-size: 14pt; margin-top: 26px; }
  .entry { padding: 9px 0; border-bottom: 1px solid #E5E7EB; }
  .entry .when { color: #6B7280; font-size: 9pt; }
  .entry .label { font-weight: 600; color: #1F2937; margin-top: 2px; }
  .entry .body { margin-top: 4px; line-height: 1.45; }
  .tag { display: inline-block; background: #EFF6FF; color: #1E40AF; padding: 1px 6px; border-radius: 3px; font-size: 8.5pt; }
  .ms-row { padding: 6px 0; border-bottom: 1px solid #F3F4F6; font-size: 10pt; }
  .ms-row .status-achieved { color: #047857; font-weight: 600; }
  .ms-row .status-in_progress { color: #D97706; font-weight: 600; }
  .ms-row .status-emerging { color: #6366F1; font-weight: 600; }
  .footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #E5E7EB; font-size: 9pt; color: #6B7280; text-align: center; }
</style></head>
<body>
  <div class="cover">
    <h1>{{ $child->first_name }} {{ $child->last_name }}</h1>
    <div class="sub">Childcare Portfolio</div>
    <div class="sub" style="margin-top: 10px;">{{ $agency->name ?? 'KiddieTrac' }}</div>
    <div class="sub" style="margin-top: 6px; font-size:9pt;">Generated {{ now()->format('F j, Y') }}</div>
  </div>

  <h2>Developmental milestones</h2>
  @forelse ($milestones as $m)
    <div class="ms-row">
      <span class="status-{{ $m->status }}">{{ str_replace('_', ' ', $m->status) }}</span> —
      <strong>{{ $m->milestone_label ?? $m->milestone_key }}</strong>
      <span class="tag">{{ $m->domain }}</span>
      <div style="color:#6B7280; font-size:9pt; margin-top:2px;">
        Observed {{ \Carbon\Carbon::parse($m->observed_at)->format('M j, Y') }}
        @if (!empty($m->notes)) — {{ $m->notes }} @endif
      </div>
    </div>
  @empty
    <div style="color:#9CA3AF; padding:10px 0;">No milestones recorded yet.</div>
  @endforelse

  <h2>Observations</h2>
  @forelse ($observations as $o)
    <div class="entry">
      <div class="when">
        {{ \Carbon\Carbon::parse($o->observed_at)->format('F j, Y \a\t g:i A') }} ·
        {{ $o->recorder ?? 'Staff' }}
        @if (!empty($o->framework)) <span class="tag">{{ $o->framework }}{{ !empty($o->domain) ? ' · ' . $o->domain : '' }}</span> @endif
      </div>
      <div class="body">{{ $o->notes }}</div>
    </div>
  @empty
    <div style="color:#9CA3AF; padding:10px 0;">No observations recorded yet.</div>
  @endforelse

  <h2>Recent daily activities</h2>
  @forelse ($logs as $l)
    <div class="ms-row">
      <strong>{{ ucfirst($l->log_type) }}</strong>
      <span class="tag">{{ \Carbon\Carbon::parse($l->occurred_at)->format('M j, g:i A') }}</span>
      @if (!empty($l->details)) — {{ $l->details }} @endif
      @if (!empty($l->notes)) <div style="font-size:9pt;color:#6B7280;margin-top:2px;">{{ $l->notes }}</div> @endif
    </div>
  @empty
    <div style="color:#9CA3AF; padding:10px 0;">No activities logged.</div>
  @endforelse

  <div class="footer">
    {{ $agency->name ?? 'KiddieTrac' }} · Portfolio generated by KiddieTrac
  </div>
</body></html>
