<!doctype html>
<html><head><meta charset="utf-8"><title>Report Card</title>
<style>
  body { font-family: 'DejaVu Sans', sans-serif; color: #1F2937; font-size: 11pt; line-height: 1.5; }
  .header { background: #1F6080; color: #fff; padding: 20px 26px; border-radius: 8px; margin-bottom: 20px; }
  .header h1 { margin: 0; font-size: 22pt; }
  .header .sub { opacity: .9; font-size: 11pt; margin-top: 4px; }
  h2 { color: #1F6080; border-bottom: 2px solid #1F6080; padding-bottom: 4px; font-size: 14pt; margin-top: 22px; }
  .meta { background: #F0F9FF; padding: 12px; border-radius: 6px; margin-bottom: 18px; font-size: 10pt; }
  .domain { padding: 14px 0; }
  .domain p { margin: 0; }
  .next-steps { background: #FFF7ED; border-left: 4px solid #F59E0B; padding: 14px; border-radius: 0 6px 6px 0; }
  .footer { margin-top: 30px; font-size: 9pt; color: #6B7280; text-align: center; }
</style></head>
<body>
  <div class="header">
    <h1>{{ $child->first_name }} {{ $child->last_name }} — Report Card</h1>
    <div class="sub">{{ $card->term }} · {{ $agency->name ?? 'KiddieTrac' }}</div>
  </div>
  <div class="meta">
    <strong>Family:</strong> {{ $family->family_name }} ·
    <strong>Issued:</strong> {{ now()->format('F j, Y') }}
  </div>

  @php
    $domains = [
      ['Belonging', $card->narrative_belonging],
      ['Well-being', $card->narrative_wellbeing],
      ['Engagement', $card->narrative_engagement],
      ['Expression', $card->narrative_expression],
    ];
  @endphp
  @foreach ($domains as [$d, $text])
    <h2>{{ $d }}</h2>
    <div class="domain"><p>{{ $text ?: 'No narrative recorded for this domain.' }}</p></div>
  @endforeach

  @if (!empty($card->next_steps))
    <h2>Next steps</h2>
    <div class="next-steps">{!! nl2br(e($card->next_steps)) !!}</div>
  @endif

  <div class="footer">
    {{ $agency->name ?? 'KiddieTrac' }} · Generated by KiddieTrac on {{ now()->format('F j, Y') }}
  </div>
</body></html>
