<!doctype html>
<html><head><meta charset="utf-8"><title>T4A Tax Receipt {{ $year }}</title>
<style>
  body { font-family: 'DejaVu Sans', sans-serif; color: #1F2937; font-size: 11pt; }
  .header { border-bottom: 2px solid #1F6080; padding-bottom: 10px; margin-bottom: 20px; }
  .header h1 { color: #1F6080; margin: 0; font-size: 22pt; }
  .agency-name { font-size: 14pt; color: #6B7280; }
  .meta { margin: 14px 0; font-size: 10pt; color: #6B7280; }
  table { width: 100%; border-collapse: collapse; margin-top: 14px; }
  th, td { padding: 7px 9px; border-bottom: 1px solid #E5E7EB; font-size: 10pt; }
  th { background: #F9FAFB; text-align: left; color: #6B7280; text-transform: uppercase; font-size: 8.5pt; }
  td.amount { text-align: right; font-variant-numeric: tabular-nums; }
  .total-row td { font-weight: bold; border-top: 2px solid #1F6080; padding-top: 9px; }
  .footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid #E5E7EB; font-size: 9pt; color: #6B7280; }
  .lead { background: #EFF6FF; padding: 12px; border-radius: 6px; margin: 16px 0; font-size: 10.5pt; }
</style></head>
<body>
  <div class="header">
    <h1>Tax Receipt — {{ $year }}</h1>
    <div class="agency-name">{{ $agency->name ?? 'KiddieTrac' }}</div>
  </div>

  <div class="meta">
    <strong>Issued to:</strong> {{ $family->family_name }}<br>
    <strong>Period:</strong> January 1 to December 31, {{ $year }}<br>
    @if (!empty($children))
      <strong>For:</strong> {{ implode(', ', $children) }}<br>
    @endif
    <strong>Receipt date:</strong> {{ now()->format('F j, Y') }}
  </div>

  <div class="lead">
    This is your official annual receipt for childcare services paid to
    {{ $agency->name ?? 'KiddieTrac' }} during {{ $year }}.
    Keep this receipt with your tax records — it supports your childcare
    expense claim on your annual T1 tax return.
  </div>

  <table>
    <thead>
      <tr><th>Date</th><th>Invoice #</th><th class="amount">Amount paid</th></tr>
    </thead>
    <tbody>
      @forelse ($payments as $p)
        <tr>
          <td>{{ \Carbon\Carbon::parse($p->paid_at)->format('M j, Y') }}</td>
          <td>{{ $p->invoice_number }}</td>
          <td class="amount">${{ number_format((float) $p->amount, 2) }}</td>
        </tr>
      @empty
        <tr><td colspan="3" style="text-align:center; color:#9CA3AF;">No payments recorded for {{ $year }}.</td></tr>
      @endforelse
      <tr class="total-row">
        <td colspan="2"><strong>Total childcare expense paid in {{ $year }}</strong></td>
        <td class="amount">${{ number_format($total, 2) }}</td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    <strong>{{ $agency->name ?? 'KiddieTrac' }}</strong><br>
    @if (!empty($agency->brand_support_email))
      Questions: {{ $agency->brand_support_email }}<br>
    @endif
    Receipt generated by KiddieTrac on {{ now()->format('F j, Y \a\t g:i A') }}.
  </div>
</body></html>
