<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * WHERE A FILED DOCUMENT CAME FROM.
 *
 * `documents` is the portal's filing cabinet -- a child's incident report, a signed NDA,
 * whatever an admin attached to somebody's record -- and until now a row said only what
 * it was, never what produced it. That was fine while every row was uploaded by hand.
 *
 * Signed forms change it. A completed form is generated by an event (a sign-off) that
 * already has its own record, and the two have to stay in step: filing the same sign-off
 * twice must not produce two documents, and re-running a backfill must be a no-op. A
 * source pair gives updateOrInsert something to key on, which is what makes both true.
 *
 * Deliberately generic rather than a managed_form_signoff_id column: the next feature
 * that files a document from a record (a payroll slip, an inspection) needs the same
 * thing, and a cabinet with one drawer named after one feature is a cabinet nobody else
 * can use. (Anthony, 2026-09-09)
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('documents', function (Blueprint $t) {
            $t->string('source_type', 40)->nullable()->after('category');
            $t->unsignedBigInteger('source_id')->nullable()->after('source_type');
            $t->index(['source_type', 'source_id'], 'documents_source_idx');
        });
    }

    public function down(): void
    {
        Schema::table('documents', function (Blueprint $t) {
            $t->dropIndex('documents_source_idx');
            $t->dropColumn(['source_type', 'source_id']);
        });
    }
};
